services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: pogchan
      POSTGRES_PASSWORD: 111844czy
      POSTGRES_DB: efiterminal
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}
