// Libs
import type { NextPage } from 'next'
import styles from '@styles/Home.module.scss'
import Head from 'next/head'
import { addApolloState, initializeApollo } from '@graphql/client/connect'
import { GetHomePageDocument, useGetHomePageQuery } from '@generated/graphql'
import { NetworkStatus } from '@apollo/client'

// Page
const Home: NextPage = () => {
  // Get home page
  const { data, networkStatus } = useGetHomePageQuery({
    variables: {
      input: {
        search: '',
      },
    },
  })

  // Return
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/public/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {networkStatus !== NetworkStatus.loading && data ? (
          <h1>{data.getHomePage?.data[0]?.title}</h1>
        ) : (
          <h3>{'Loading...'}</h3>
        )}
      </main>
    </div>
  )
}

export default Home

// Ssr
// export async function getStaticProps() {
//   const apolloClient = initializeApollo()
//
//   await apolloClient.query({
//     query: GetHomePageDocument,
//     variables: {
//       input: {
//         search: '',
//       },
//     },
//   })
//
//   return addApolloState(apolloClient, {
//     props: {},
//     revalidate: 60,
//   })
// }
